In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from tkinter import *
from tkinter import messagebox

dataset_url = r"C:\heart_ds\heart.csv"
dataset_df = pd.read_csv(dataset_url)
dataset_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [2]:
dataset_df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [3]:
dataset_df.shape

(1025, 14)

In [4]:
dataset_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [5]:
dataset_df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [6]:
X = dataset_df.iloc[:, :-1].values
y = dataset_df.iloc[:, -1].values

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2 , random_state = 0 )

In [8]:
print(X_train)

[[42.  1.  3. ...  2.  2.  2.]
 [66.  0.  2. ...  1.  1.  2.]
 [53.  1.  2. ...  2.  3.  2.]
 ...
 [65.  1.  3. ...  1.  1.  2.]
 [67.  1.  0. ...  1.  0.  2.]
 [60.  1.  2. ...  1.  0.  2.]]

In [9]:
print(y_train)

[1 1 1 1 0 1 0 1 0 0 0 1 0 1 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 1 0 1 1 0 0 0 0
 0 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0 1 0 0 1 1
 1 0 1 1 0 1 0 0 1 1 1 0 1 0 1 0 1 0 1 0 1 1 0 1 1 1 0 1 0 1 0 1 0 1 1 1 1
 0 1 0 1 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 0 1 1 1 0 1 0 1 0 1 1 1 1 0 0 0 0 0
 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1
 1 0 0 1 0 0 1 1 1 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 1 1 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 1 0 1 1 0 1 1 1 0 1 1 0 1 1 0 1 0 1 1 1
 1 0 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 1 1 1 0 1 0
 1 0 1 1 1 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0 1 0 0
 1 0 1 0 1 0 0 0 0 1 0 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 0 0 1 1 0 0 1 1 0 1
 1 1 0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 1
 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 1
 0 1 1 0 1 0 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 1 1 0
 1 0 1 0 1 0 0 0 0 1 1 0 0 1 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0
 0 1 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 1 0 1 1
 0 0 1 1 1 0 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 1 0 1 1 0 1 0 0 1 1 0 1 0 1 1 1
 0 1 0 0 0 0 1 1 0 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 0 0 1 0 1
 0 1 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 1 0 0 1 1 0
 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 1 0 1 1 0 0 1 1 0
 1 0 0 0 1 0 1 0 1 1 0 1 1 1 0 1 1 1 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 0 1 1 0
 1 0 0 1 0 0 0 0 1 0 1 0 1 1 1 0 0 1 0 1 1 0 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0
 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 1 0 1 0 0 0]

In [10]:
print(X_test)

[[44.  1.  2. ...  2.  0.  2.]
 [58.  0.  1. ...  2.  2.  2.]
 [63.  1.  0. ...  2.  2.  3.]
 ...
 [43.  0.  2. ...  1.  0.  2.]
 [66.  0.  0. ...  1.  2.  3.]
 [71.  0.  0. ...  1.  0.  2.]]

In [11]:
print(y_test)

[1 0 0 1 0 0 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 0
 0 1 1 0 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 1 1 1 1 1 0
 0 0 0 1 0 0 0 0 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 1 1 1 0 0 1 0 1 0 1 1
 0 1 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 1 1 0 1 0 0 1 1 1
 1 0 1 1 1 0 0 0 1 1 0 0 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1
 0 1 0 1 0 0 1 0 1 0 1 1 1 0 0 1 1 1 0 1]

In [12]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[-1.40503359  0.64895597  1.97748631 ...  0.97028605  1.17427458
  -0.5144228 ]
 [ 1.26270023 -1.5409366   1.01170979 ... -0.6668221   0.21616
  -0.5144228 ]
 [-0.18232226  0.64895597  1.01170979 ...  0.97028605  2.13238916
  -0.5144228 ]
 ...
 [ 1.15154465  0.64895597  1.97748631 ... -0.6668221   0.21616
  -0.5144228 ]
 [ 1.3738558   0.64895597 -0.91984324 ... -0.6668221  -0.74195458
  -0.5144228 ]
 [ 0.59576677  0.64895597  1.01170979 ... -0.6668221  -0.74195458
  -0.5144228 ]]

In [14]:
print(X_test)

[[-1.18272244  0.64895597  1.01170979 ...  0.97028605 -0.74195458
  -0.5144228 ]
 [ 0.37345562 -1.5409366   0.04593327 ...  0.97028605  1.17427458
  -0.5144228 ]
 [ 0.9292335   0.64895597 -0.91984324 ...  0.97028605  1.17427458
   1.10177143]
 ...
 [-1.29387801 -1.5409366   1.01170979 ... -0.6668221  -0.74195458
  -0.5144228 ]
 [ 1.26270023 -1.5409366  -0.91984324 ... -0.6668221   1.17427458
   1.10177143]
 [ 1.81847811 -1.5409366  -0.91984324 ... -0.6668221  -0.74195458
  -0.5144228 ]]

In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=2 , metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

In [16]:
print(knn.predict(sc.transform([[53, 1, 0, 140, 203, 1, 0, 155, 1, 3.1, 0, 0, 3]])))

[0]

In [17]:
y_pred = knn.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]]

In [18]:
#making confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[ 98   0]
 [  2 105]]

0.9902439024390244

In [19]:
root = Tk()
root.title(' KNN-Classification Heart Disease ')
root.config(background="#66b3ff")
button_color = "#66b3ff"  
root.resizable(True, True)
root.minsize(width=600, height=400)
root.maxsize(width=1000, height=600)

In [20]:
def predict():
        # Get user input from entry fields
        age = int(age_entry.get())
        sex = int(sex_entry.get())
        cp = int(cp_entry.get())
        trestbps = int(trestbps_entry.get())
        chol = int(chol_entry.get())
        fbs = int(fbs_entry.get())
        restecg = int(restecg_entry.get())
        thalach = int(thalach_entry.get())
        exang = int(exang_entry.get())
        oldpeak = float(oldpeak_entry.get())
        slope = int(slope_entry.get())
        ca = int(ca_entry.get())
        thal = int(thal_entry.get())
        
        prediction_new_point=knn.predict(sc.transform([[age, sex, cp, trestbps, chol ,fbs, restecg, thalach, exang, oldpeak, slope, ca, thal]])) 
        
        result_text = "Predicted Heart Disease: Yes ! It's crucial to consult a doctor for further evaluation !" if prediction_new_point == 1 else "Predicted Heart Disease: No"
        messagebox.showinfo(" Predicting Result ", result_text) 
  
label_padx = 65  # Padding between label and entry
entry_width = 30  # Width of entry fields  

age_label = Label(root, text=" Age:")
age_label.grid(row=0, column=0,padx=label_padx , pady=10 )
age_entry = Entry(root,width=entry_width)
age_entry.grid(row=0, column=1)

sex_label = Label(root, text=" Sex (Male=0, Female=1): ")
sex_label.grid(row=1, column=0,padx=label_padx)
sex_entry = Entry(root,width=entry_width)
sex_entry.grid(row=1, column=1)

cp_label = Label(root, text=" Chest pain type: ")
cp_label.grid(row=2, column=0,padx=label_padx, pady=10)
cp_entry = Entry(root,width=entry_width)
cp_entry.grid(row=2, column=1)

trestbps_label = Label(root, text=" Resting blood pressure: ")
trestbps_label.grid(row=3, column=0,padx=label_padx)
trestbps_entry = Entry(root,width=entry_width)
trestbps_entry.grid(row=3, column=1)

chol_label = Label(root, text=" cholestrol: ")
chol_label.grid(row=4, column=0,padx=label_padx, pady=10)
chol_entry = Entry(root,width=entry_width)
chol_entry.grid(row=4, column=1)

fbs_label = Label(root, text=" Fasting blood sugar: ")
fbs_label.grid(row=5, column=0,padx=label_padx)
fbs_entry = Entry(root,width=entry_width)
fbs_entry.grid(row=5, column=1)

restecg_label = Label(root, text=" Resting electrocardiographic results (values 0,1,2): ")
restecg_label.grid(row=6, column=0,padx=label_padx, pady=10)
restecg_entry = Entry(root,width=entry_width)
restecg_entry.grid(row=6, column=1)

thalach_label = Label(root, text=" Maximum heart rate achieved: ")
thalach_label.grid(row=7, column=0,padx=label_padx)
thalach_entry = Entry(root,width=entry_width)
thalach_entry.grid(row=7, column=1)

exang_label = Label(root, text=" Exercise induced angina: ")
exang_label.grid(row=8, column=0,padx=label_padx, pady=10)
exang_entry = Entry(root,width=entry_width)
exang_entry.grid(row=8, column=1)

oldpeak_label = Label(root, text=" ST: ")
oldpeak_label.grid(row=9, column=0,padx=label_padx)
oldpeak_entry = Entry(root,width=entry_width)
oldpeak_entry.grid(row=9, column=1)

slope_label = Label(root, text=" slope: ")
slope_label.grid(row=10, column=0,padx=label_padx, pady=10)
slope_entry = Entry(root,width=entry_width)
slope_entry.grid(row=10, column=1)

ca_label = Label(root, text=" Number of major vessels (0-3): ")
ca_label.grid(row=11, column=0,padx=label_padx)
ca_entry = Entry(root,width=entry_width)
ca_entry.grid(row=11, column=1)

thal_label = Label(root, text=" Thallium stress test (values 0,1,2): ")
thal_label.grid(row=12, column=0,padx=label_padx, pady=10)
thal_entry = Entry(root,width=entry_width)
thal_entry.grid(row=12, column=1)

button_padx = 15  # Padding around the button
button_pady = 20  # Space between button and bottom
button_width = 20  # Increased width for the button
predict_button = Button(root, text=" Predict ", command=predict, width=button_width ) #, bg=button_color)
predict_button.grid(row=13, columnspan=2, padx=button_padx, pady=button_pady)

# Predict button
root.mainloop()